### PR TITLE
Added Contentful and Netlify CMS to the list of CMSes, Added a new section for FaaS

### PR DESCRIPTION
**Pull request by jhnsntmthy**
Contentful is big and expensive, but a good service to include here. 
Netlify is building their own opensource CMS and it looks to be really great.

### CODE REVIEW

**Comment by jhnsntmthy** [comment]
I was surprised to find out you left out the entire section on FaaS, which is what a lot of the movement is toward serverless static sites these days... But then a lot has happened this year and last year this was not the rage.

In keeping with your idea of making this list easy to contribute to, (since I found it through the article on CloudCannon), would you be amenable to me creating a static site out of this list? My idea would be to incorporate a static CMS with it so that people without GH could contribute (but whoever doesn't have GH, why would they?) from the website and the community could upvote, recommend, comment on each of these services? If you would like to hack on it with me, that would be great, or I can just work on it by myself...

**Comment by aharris88** [comment]
Yeah, that would be great to have a static site for this list. Go ahead and get started if you want and hopefully I can help out.

**Comment by aharris88** [comment]
It looks like you removed the URL for Forestry?

**Comment by jhnsntmthy** [comment]
Cool thanks, I will get going on that, and we'll just add community and voting as we go.

**Comment by jhnsntmthy** [comment]
readded forestry, was an accident, thanks for pointing it out

**Pull request merged**
