### PR TITLE
Update redirects in Readme

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### CODE REVIEW

**Comment by aharris88** [comment]
Thanks.

**Comment by ReadmeCritic** [comment]
:wink:

**Comment by aharris88** [comment]
Can you look at this one too? https://github.com/aharris88/awesome-mac-screensavers

**Comment by ReadmeCritic** [comment]
No errors for 38 links 😎 
https://gist.github.com/ReadmeCritic/1b86bf2559ab92285732

**Pull request merged**
