### PR TITLE
Update README.md with Silex and Forge

### PR DESCRIPTION
**Pull request by lexoyo**
Very useful links for Silex users, thanks
Added Silex and Forge info

### CODE REVIEW

**Comment by lexoyo** [comment]
Sorry for making 2 additions in 1 PR :8ball:

**Comment by aharris88** [comment]
I'll add forge, but I'm not sold on Silex. I'll need to do more research on it. I try to only add things to the list that are awesome.

**Comment by aharris88** [comment]
I added Forge.

**Comment by lexoyo** [comment]
No Silex? Not awesome? :)

**Comment by aharris88** [comment]
Yeah, I'm not convinced. I'm happy to be proved wrong though, especially if I start getting more requests to add it.

**Pull request closed without merging**
